### PR TITLE
Added badges to the recent content

### PR DESCRIPTION
**Pull request by ajeetraina**
This PR adds a "new" badge to the recently published content

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]
LGTM!

My only concern is that those badges will be outdated soon, but this is expected to be reviewed and changed with certain frequency by the community, right?

**Comment by ajeetraina** [comment]
That’s right. We will need to update it accordingly as new resources and links get introduced. We can mark the resources “new” if the created date is not more than last 4 months. WDYT?

**Comment by mdelapenya** [comment]
> We can mark the resources “new” if the created date is not more than last 4 months.

Yeah, do we need to advertise that in any place? Here in the README, as a github label? Do you have an idea that could work for this?

**Comment by mdelapenya** [comment]
BTW, merging, and moving the discussion to a separate issue/discussion.

Thanks!

**Pull request merged**
