### PR TITLE
Closed issue 24 and 20

### PR DESCRIPTION
**Pull request by alwinhb**
Added video link and Developer Stories Section

### CODE REVIEW

**Comment by mdelapenya** [comment]
@alwinhb could you please resolve the conflicts before we review them? 🙏 

Thanks for your time!

**Comment by alwinhb** [comment]
@mdelapenya I have added a new section, I think that is causing the conflict. 

This section (Developer Stories) needs to be added

**Comment by mdelapenya** [comment]
Yeah, thanks for adding the section. I'd expect your PR used the current main as base so that there is no conflicts with the current main branch. Could you rebase and add your commits on top of it?

Cheers!

**Comment by alwinhb** [comment]
Closed this PR . Took a SYNC and added changes in new PR

**Pull request closed without merging**
